/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.description.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class DescriptionFileIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new DescriptionFileStandaloneSetupIdea().createInjector
	}

}
