/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.description.idea

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class DescriptionFileIdeaModule extends AbstractDescriptionFileIdeaModule {
}
