/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.capability

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NodeCapabilityFileStandaloneSetup extends NodeCapabilityFileStandaloneSetupGenerated {

	def static void doSetup() {
		new NodeCapabilityFileStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
