/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.description

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DescriptionFileStandaloneSetup extends DescriptionFileStandaloneSetupGenerated {

	def static void doSetup() {
		new DescriptionFileStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
