/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.capability.idea.completion

import com.ptransportation.capability.idea.lang.NodeCapabilityFileLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class NodeCapabilityFileCompletionContributor extends AbstractNodeCapabilityFileCompletionContributor {
	new() {
		this(NodeCapabilityFileLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
