/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.description.idea.lang

class DescriptionFileFileType extends AbstractDescriptionFileFileType {
	public static final DescriptionFileFileType INSTANCE = new DescriptionFileFileType()
	
	new() {
		super(DescriptionFileLanguage.INSTANCE)
	}
}
