/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.description.idea.completion

import com.ptransportation.description.idea.lang.DescriptionFileLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class DescriptionFileCompletionContributor extends AbstractDescriptionFileCompletionContributor {
	new() {
		this(DescriptionFileLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
