/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.capability.idea

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class NodeCapabilityFileIdeaModule extends AbstractNodeCapabilityFileIdeaModule {
}
