/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.capability.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class NodeCapabilityFileIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new NodeCapabilityFileStandaloneSetupIdea().createInjector
	}

}
