/*
 * generated by Xtext 2.9.1
 */
package com.ptransportation.capability.idea.lang

class NodeCapabilityFileFileType extends AbstractNodeCapabilityFileFileType {
	public static final NodeCapabilityFileFileType INSTANCE = new NodeCapabilityFileFileType()
	
	new() {
		super(NodeCapabilityFileLanguage.INSTANCE)
	}
}
